### PR TITLE
ESM support for #1033

### PR DESCRIPTION
**Pull request by palewire**
I taken some large steps to port forward our imports to the new ESM system. You can see those here.

Along the way though, I've run into some roadblocks that I'm unsure about how to properly handle. I'm hoping @rdmurphy can consult.

My biggest question right now: How to handle the `require.resolve` type imports happening inline in several of the engines. I suspect these are being used, at least in some cases, as part of a lazy loading scheme. Whatever the intention, I'm unsure about the proper way to port forward these techniques to comply with ESM.

Any advice here would be appreciated. I'm happy to implement. An example of what I'm talking about can be found [here](https://github.com/datadesk/baker/blob/main/lib/engines/rollup.js#L125)

### CODE REVIEW

**Comment by rdmurphy** [comment]
👋 I was gonna take a closer look this weekend but for that `require.resolve` issue you can recreate a functioning `require` that supports `resolve` in ESM with [`module.createRequire`](https://nodejs.org/api/module.html#modulecreaterequirefilename).

**Comment by palewire** [comment]
Cool. I'll can fumbling around if it's on your agenda. I think there's just a couple subtle internal things like that hack out and we're probably there.

**Comment by rdmurphy** [comment]
Okay! I did a pass on the converted imports just to make sure everything was in order and it was mostly good to go! Looks like tests are happy too. I removed that package for imports in favor of the native way to re-add `require.resolve`. I also swapped in `html-minifier-terser` for `html-minifier` — the previous one is still using an ancient JS minify library and is mostly abandon ware now so this upgrade sidesteps that. Other than being actively updated the new package is identical.

**Comment by palewire** [comment]
Thank you! I'll try to get all this merged in, etc.

**Comment by palewire** [comment]
Here's an issue. I converted the package.json to `type: 'module'`, as called for by the imagemin upgrade guide. That appears to be causing a problem with our `pre-commit` hooks:

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/palewire/Code/baker/.git/hooks/_detect_package_hooks
```

Not sure the best play here, but I think it's something about the ESM stuff not jelling with those hooks. I suspect you didn't run into it because I had removed the pre-commit step from the package.json when I was hacking around. Not that I've added it back in, I'm having the issue again.

**Comment by palewire** [comment]
For now, I'm going to leave the hooks out.

**Comment by rdmurphy** [comment]
Ack I forgot about the hooks. I fixed that locally but forgot to note it. That issue is only a local one, and it depends on whether you previously ran `npm install` before the swap to modules. That library doesn't know it happened and just sees those hooks as present and leaves them as-is.

The way to fix that is to wipe out your git hooks for the repo (`rm .git/hooks/*`) and re-run `npm install` so they get set back up.

But while we're here — they've actually moved that package to a new namespace so I'd suggest if we re-add we swap to the actively maintained one: https://www.npmjs.com/package/@vercel/git-hooks

**Comment by palewire** [comment]
Cool. Sounds fixable then. Thanks for the info. I'll try to fix it and then merge into main.

**Comment by palewire** [comment]
Yep. That did it. My hooks are working again, and we've upgraded to the new vercel namespace.

**Review by rdmurphy — APPROVED** [review]

**Pull request merged**
